<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Facepunch.Steamworks.Dll" Version="1.62.0" />
    <PackageReference Include="Steamworks.NET" Version="2024.8.0" />
  </ItemGroup>

</Project>
